version: '3.9'
services:
  api:
    build: ./server
    ports:
      - '8080:8080'
    environment:
      - PG_HOST=db
      - PG_PASSWORD=${PG_PASSWORD}
  db:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DB=taskcodee
      - POSTGRES_PASSWORD=${PG_PASSWORD}
