services:
  - type: web
    name: api
    env: docker
    rootDir: server
    region: frankfurt
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PG_HOST
        fromDatabase:
          name: db
          property: host
      - key: PG_PORT
        fromDatabase:
          name: db
          property: port
      - key: PG_PASSWORD
        fromDatabase:
          name: db
          property: password
      - key: PG_USER
        fromDatabase:
          name: db
          property: user
      - key: PG_DATABASE
        fromDatabase:
          name: db
          property: database
  - type: web
    name: client
    env: static
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: ./dist

databases:
  - name: db
    region: frankfurt
    plan: free
